var res = {
    MainScene_json : "res/arts/MainScene.json",
    MainSceneLayer_json:"res/arts/MainSceneLayer.json",
    TradingHallLayer_json:"res/arts/TradingHallLayer.json",
    LoginLayer_json:"res/arts/LoginLayer.json",
    ProductEdit_json:"res/arts/ProductEdit.json",
    TradeSettleLayer_json:"res/arts/TradeSettleLayer.json",
    UserDetail_json:"res/arts/UserDetailLayer.json",
    RechargeLayer_json:"res/arts/RechargeLayer.json",
    WebPayLayer_json:"res/arts/WebPayLayer.json",
    PayPasswordSetLayer_json:"res/arts/PayPasswordSetLayer.json",
    PayPasswordVerifyLayer_json:"res/arts/PayPasswordVerifyLayer.json",
    CashOutLayer_json:"res/arts/CashOutLayer.json",
    LoadingLayer_json:"res/arts/LoadingLayer.json",
    AssistantAvatar_json:"res/arts/AssistantAvatar.json",
    LoginTypeLayer_json:"res/arts/LoginTypeLayer.json",
    SliderBar_json:"res/arts/SliderBar.json",
    ClientLogLayer_json:"res/arts/ClientLogLayer.json",
    RankLayer_json:"res/arts/RankLayer.json",
    MoneyFlowLayer_json:"res/arts/MoneyFlowLayer.json",
    UserFeedbackLayer_json:"res/arts/UserFeedbackLayer.json",
    SetLayer_json:"res/arts/SetLayer.json",
    TradeModeCell_json:"res/arts/TradeModeCell.json",
    BetDetail_json:"res/arts/BetDetail.json",
    MailLayer_json:"res/arts/MailLayer.json",
    MailCell_json:"res/arts/MailCell.json",
    TradeControlNormal_json:"res/arts/TradeControlNormal.json",
    TradeControlGlobal_json:"res/arts/TradeControlGlobal.json",
    TradeControlHighLowList_json:"res/arts/TradeControlHighLowList.json",
    TradeControlHighLowListFee_json:"res/arts/TradeControlHighLowListFee.json",
    TradeControlSelectedCell_json:"res/arts/TradeControlSelectedCell.json",
    TradeControlTouchOffsetChoose_json:"res/arts/TradeControlTouchOffsetChoose.json",
    TradeControlTouchOffsetFee_json:"res/arts/TradeControlTouchOffsetFee.json",
    GlobalBetConfirm_json:"res/arts/GlobalBetConfirm.json",
    DownLoadProgress_json:"res/arts/DownLoadProgress.json",
    VerificationCode_json:"res/arts/VerificationCode.json",
    MenuAllCell_json:"res/arts/MenuAllCell.json",
    RedPacket_json:"res/arts/RedPacketLayer.json",
    RedPacketRecord_json:"res/arts/RedPacketRecord.json",
    RedPacketCell_json:"res/arts/RedPacketCell.json",
    GeneralClickEffect_json:"res/arts/GeneralClickEffect.json",
    TradeChartSelect_json:"res/arts/TradeChartSelect.json",
    RoomManagement_json:"res/arts/RoomManagement.json",
    RoomChoose_json:"res/arts/RoomChoose.json",
    RoomApplyCell_json:"res/arts/RoomApplyCell.json",
    RoomApply_json:"res/arts/RoomApply.json",
    RoomCreate_json:"res/arts/RoomCreate.json",
    RoomManageGBCell_json:"res/arts/RoomManageGBCell.json",
    RoomShare_json:"res/arts/RoomShare.json",
    RoomFindRoom_json:"res/arts/RoomFindRoom.json",
    RoomApplyHintCell_json:"res/arts/RoomApplyHintCell.json",
    RoomChooseCell_json:"res/arts/RoomChooseCell.json",
    WebShopLayer_json:"res/arts/WebShopLayer.json",
    ShareLayer_json:"res/arts/ShareLayer.json",
    SplitInvitationCodeView_json:"res/arts/SplitInvitationCodeView.json",

    LoginBgAnimation_json:"res/arts/LoginBgAnimation.json",
    UserInfoAuthentication_json:"res/arts/UserInfoAuthentication.json",
    IDCardUpLoadLayer_json:"res/arts/IDCardUpLoadLayer.json"


};

var g_resources = [];
for (var i in res) {
    g_resources.push(res[i]);
}