/**
 * notification key
 * Created by Administrator on 2016/5/6.
 */

var NOTIFY_PER_ONE_SECOND = "NOTIFY_PER_ONE_SECOND";        //全局的每秒通知
var NOTIFY_GAME_ON_SHOW = "game_on_show";//游戏从后台回到前台时会通知
var NOTIFY_GAME_ON_HIDE = "game_on_hide";
var NOTIFY_ENTER_MAIN_SCENE = "ENTER_MAIN_SCENE"; //进入主界面
//var NOTIFY_DO_BET_ESTIMATE_RISE = "NOTIFY_DO_BET_ESTIMATE_RISE";  //看涨
//var NOTIFY_DO_BET_ESTIMATE_FALL = "NOTIFY_DO_BET_ESTIMATE_FALL"; //看跌
var NOTIFY_DO_BET = "NOTIFY_DO_BET"; //下单
var NOTIFY_REFRESH_FETCH_AVATAR = "NOTIFY_REFRESH_FETCH_AVATAR";        //有新的抓取用户了
var NOTIFY_REMOVE_SELECTED_PRODUCT = "NOTIFY_REMOVE_SELECTED_PRODUCT";  //移除被选择的产品
var NOTIFY_ADD_SELECTED_PRODUCT = "NOTIFY_ADD_SELECTED_PRODUCT";        //添加选择的产品
var NOTIFY_PRODUCT_TID_CHANGE = "NOTIFY_PRODUCT_TID_CHANGE";            //产品类型选择变更
var NOTIFY_PRODUCT_SELECT_CHANGE = "NOTIFY_PRODUCT_SELECT_CHANGE";      //产品切换
var NOTIFY_FORCE_REFRESH_TRADE = "NOTIFY_FORCE_REFRESH_TRADE";          //强制重新刷新交易
var NOTIFY_TRADING_HALL_USER_FETCH = "NOTIFY_TRADING_HALL_USER_FETCH";  //触发交易大厅调用用户抓取
var NOTIFY_BET_RESULT_COIN_ANIMATE = "NOTIFY_BET_RESULT_COIN_ANIMATE";  //触发金钱动画
var NOTIFY_RISE_FALL_PERCENT = "NOTIFY_RISE_FALL_PERCENT";              //看涨看跌百分比变化通知
var NOTIFY_SHOW_BET_HISTORY = "NOTIFY_SHOW_BET_HISTORY";                //显示下单历史通知
var NOTIFY_SHOW_DYNAMIC_QUOTE = "NOTIFY_SHOW_DYNAMIC_QUOTE";            //通知交易大厅显示当前行情(最新行情)
var NOTIFY_ODDS_CHANGES = "NOTIFY_ODDS_CHANGES";                        //赔率更新

var NOTIFY_CLOSE_USER_DETAIL = "NOTIFY_CLOSE_USER_DETAIL";                  //关闭用户详细信息面板
var NOTIFY_REFRESH_ACCOUNT_DETAIL = "NOTIFY_REFRESH_ACCOUNT_DETAIL";        //请求刷新用户账户信息
var NOTIFY_REFRESH_USER_TEST_COIN = "NOTIFY_REFRESH_USER_TEST_COIN";        //模拟币变化
var NOTIFY_REFRESH_USER_BALANCE = "NOTIFY_REFRESH_USER_BALANCE";             //资金变化

var NOTIFY_REFRESH_USER_BASE = "NOTIFY_REFRESH_USER_BASE";                   //请求刷新用户基础信息（昵称、头像。。。）
var NOTIFY_REFRESH_USER_NICK_NAME = "NOTIFY_REFRESH_USER_NICK_NAME";         //昵称变化
var NOTIFY_RECHARGE_RESULT = "NOTIFY_RECHARGE_RESULT";                       //充值结果通知
var NOTIFY_ADD_FETCH_PLAYER = "NOTIFY_ADD_FETCH_PLAYER";                     //新增抓取用户
var NOTIFY_REMOVE_FETCH_PLAYER = "NOTIFY_REMOVE_FETCH_PLAYER";               //移除抓取用户

var NOTIFY_REFRESH_RANK_LIST = "NOTIFY_REFRESH_RANK_LIST";             // 刷新榜单

var NOTIFY_UPLOAD_FILE_SUCCESS = "NOTIFY_UPLOAD_FILE_SUCCESS";              //文件上传成功
var NOTIFY_SELF_AVATAR_CHANGES = "NOTIFY_SELF_AVATAR_CHANGES";              //头像修改成功

var ASST_INFO_EVENT = "ASST_INFO_EVENT";                                //助手事件
var NOTIFY_QUOTE_UPDATE = "NOTIFY_QUOTE_UPDATE";                        //行情更新
var NOTIFY_PRODUCT_INFO_UPDATE = "NOTIFY_PRODUCT_INFO_UPDATE";          //产品信息更新
var NOTIFY_ORDER_COUNT = "NOTIFY_ORDER_COUNT";                          //订单结算
var NOTIFY_NEW_ORDER = "NOTIFY_NEW_ORDER";                              //新订单
var NOTIFY_FETCH_FULL_PLAYERS = "NOTIFY_FETCH_FULL_PLAYERS";            //抓取满屏用户通知
var NOTIFY_FETCH_NEW_ORDER = "NOTIFY_FETCH_NEW_ORDER";                  //抓用户下单
var NOTIFY_NOTICE = "NOTIFY_NOTICE";                                    //公告
var NOTIFY_ONLINE_NUM_UPDATE = "NOTIFY_ONLINE_NUM_UPDATE";              //在线人数
var NOTIFY_REFRESH_LOGIN_STATE = "NOTIFY_REFRESH_LOGIN_STATE";          //刷新用户登录状态
var NOTIFY_SWITCH_TRADE_MODE = "NOTIFY_SWITCH_TRADE_MODE";

var NOTIFY_FETCH_PLAYER_CHANGES = "NOTIFY_FETCH_PLAYER_CHANGES";        //抓取用户有变动了
var NOTIFY_POSITION_CHANGES = "NOTIFY_POSITION_CHANGES";                //持仓数变更
var NOTIFY_QUOTE_EXCEPTION = "NOTIFY_QUOTE_EXCEPTION";                  //行情异常
var NOTIFY_FEEDBACK = "NOTIFY_FEEDBACK";                                //客服反馈
var NOTIFY_PRODUCT_TRADE_START = "NOTIFY_PRODUCT_TRADE_START";          //产品开始通知
var NOTIFY_NEW_MAIL = "NOTIFY_NEW_MAIL";                                //新邮件
var NOTIFY_USER_DETAIL_OPENED = "NOTIFY_USER_DETAIL_OPENED";            //打开用户详情
var NOTIFY_RED_DOT = "NOTIFY_RED_DOT";                                  //红点
var NOTIFY_ROOM_NEW_JOIN_APPLY = "NOTIFY_ROOM_NEW_JOIN_APPLY";          //房间新的申请信息
var NOTIFY_ROOM_DEL_JOIN_APPLY = "NOTIFY_ROOM_DEL_JOIN_APPLY";          //房间邀请信息已经被其他管理员处理
var NOTIFY_ROOM_JOIN_APPLY_RESULT = "NOTIFY_ROOM_JOIN_APPLY_RESULT";    //玩家申请房间消息回馈
var NOTIFY_ROOM_STATE_CHANGE = "NOTIFY_ROOM_STATE_CHANGE";              //进入房间
var NOTIFY_ROOM_ID_LIST_UPDATE = "NOTIFY_ROOM_ID_LIST_UPDATE";          //房间idList更新
var NOTIFY_ROOM_NAME_CHANGE = "NOTIFY_ROOM_NAME_CHANGE";                //房间名更新
var NOTIFY_QUIT_ROOM = "NOTIFY_QUIT_ROOM";                              //退出房间

var NOTIFY_SHOW_TRADE_LIST = "NOTIFY_SHOW_TRADE_LIST";                  //显示订单列表
var NOTIFY_SHOW_TRADE_CONTROL = "NOTIFY_SHOW_TRADE_CONTROL";            //显示下单面板
var NOTIFY_PRODUCT_EDIT_ON_SHOW = "NOTIFY_PRODUCT_EDIT_ON_SHOW";        //显示编辑界面的时候
var NOTIFY_CHART_SELECT_CHANGES = "NOTIFY_CHART_SELECT_CHANGES";        //图表变动
var NOTIFY_CHART_CLOSE = "NOTIFY_CHART_CLOSE";                          //图表关闭
var NOTIFY_CHART_ITEM_SELECT_CHANGES = "NOTIFY_CHART_ITEM_SELECT_CHANGES";//图表项区间选择改变
var NOTIFY_LAYER_CLOSE = "NOTIFY_LAYER_CLOSE";                          //界面关闭
var NOTIFY_LAYER_OPEN = "NOTIFY_LAYER_OPEN";                            //界面打开
var NOTIFY_TCP_AUTH_SUCCESS = "NOTIFY_TCP_AUTH_SUCCESS";                //tcp认证成功
var NOTIFY_TCP_DISCONNECTED = "socket_event_disconnect";                //tcp断开连接了
var NOTIFY_PRODUCT_CHANGE = "NOTIFY_PRODUCT_CHANGE";
var NOTIFY_BET_BE_SELECTED = "NOTIFY_BET_BE_SELECTED";
var NOTIFY_ROOM_DEL_MEMBER = "NOTIFY_ROOM_DEL_MEMBER";
var NOTIFY_ROOM_NEW_MEMBER = "NOTIFY_ROOM_NEW_MEMBER";
var NOTIFY_ROOM_TRADE_ORDER = "NOTIFY_ROOM_TRADE_ORDER";
var NOTIFY_PRODUCT_REMOVED = "NOTIFY_PRODUCT_REMOVED";
var NOTIFY_ROOM_BASIC_CHANGE = "NOTIFY_ROOM_BASIC_CHANGE";
var NOTIFY_ROOM_ORDER_REFRESH = "NOTIFY_ROOM_ORDER_REFRESH";
var NOTIFY_ROOM_ORDER_COUNT = "NOTIFY_ROOM_ORDER_COUNT";
var NOTIFY_ROOM_CHOOSE_REFRESH =  "NOTIFY_ROOM_CHOOSE_REFRESH";
var NOTIFY_ROOM_PROFILE_UPDATE  = "NOTIFY_ROOM_PROFILE_UPDATE";